# Copy this file to .streamlit/secrets.toml for local development
# For Streamlit Cloud, add these secrets in the app dashboard

OPENROUTER_API_KEY = "your_openrouter_api_key_here"
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
DEFAULT_MODEL = "deepseek/deepseek-r1-0528:free"
JINA_API_KEY = "your_jina_api_key_here"
